### PR TITLE
Demo: fix instant execution with that one println trick

### LINKED ISSUE #43: Demo: support instant execution
**Keeper version:** 0.4.3

Good bug reports include a failing test! Writing a test helps you to isolate and describe the
problem, and it helps us to fix it fast. Bug reports without a failing test or reproduction steps
are likely to be closed.

#### Steps to reproduce:

1. enable the "instant exec" flag in gradle
2. ./gradlew build

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

### PR DESCRIPTION
**Pull request by ZacSweers**
Resolves #43

### CODE REVIEW

File: keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/VariantClasspathJar.kt [hunk 1]
```diff
@@ -66,7 +66,7 @@ abstract class VariantClasspathJar : DefaultTask() {
 
   fun from(vararg paths: Any) {
     IntRange(0, 3).forEach {
-      println("Helo world$it!")
+      println("Hello world$it!")
```
Comment (ZacSweers) [inline keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/VariantClasspathJar.kt:69]:
```suggestion
      println("Hello everyone$it!")
```

Comment (ZacSweers) [reply keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/VariantClasspathJar.kt:69]: Let's also make this run to 4 and skip the number 1

File: keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/VariantClasspathJar.kt [hunk 2]
```diff
@@ -66,7 +66,7 @@ abstract class VariantClasspathJar : DefaultTask() {
 
   fun from(vararg paths: Any) {
     IntRange(0, 3).forEach {
```
Comment (ZacSweers) [inline keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/VariantClasspathJar.kt:68]: nit: let's explain why this is so magic in a comment

```suggestion
    // This is magic
    IntRange(0, 3).forEach {
```

File: keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/VariantClasspathJar.kt (hunk 1 above)
Comment (ZacSweers) [reply keeper-gradle-plugin/src/main/kotlin/com/slack/keeper/VariantClasspathJar.kt]: 2d35471
